### ISSUE TITLE
Getting Token Error

### ISSUE THREAD

**Issue by lilRufi** [ChristopherBThai/Discord-OwO-Bot#145]
I was trying to self-host the OwO bot but I was geting an error(s).

```
[16:01:54] General | Cluster Manager has started!
[16:01:54] Cluster Manager | Starting 1 shards in 1 clusters
[16:01:54] Cluster Manager | Launching cluster 0
[16:01:54] Cluster Manager | Clusters have been launched!
[16:01:54] Cluster Manager | All shards spread
Creating shards 0~1 out of 1 total shards!
[16:01:55] Cluster 0 | Connecting with 2 shard(s)
[16:01:55] Cluster 0 | Shard 0 established connection!
[16:01:55] Cluster 0 | Shard undefined | Error: Invalid token: Bot undefined
    at Shard._onWSClose (C:\Users\Rauf\paradox\Discord-OwO-Bot\node_modules\eris\lib\gateway\Shard.js:2058:36)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (C:\Users\Rauf\paradox\Discord-OwO-Bot\node_modules\ws\lib\websocket.js:194:10)
    at TLSSocket.socketOnClose (C:\Users\Rauf\paradox\Discord-OwO-Bot\node_modules\ws\lib\websocket.js:861:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)
[16:01:55] Cluster 0 | Shard 0 | Error: Authentication failed
    at Shard._onWSClose (C:\Users\Rauf\paradox\Discord-OwO-Bot\node_modules\eris\lib\gateway\Shard.js:2055:23)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (C:\Users\Rauf\paradox\Discord-OwO-Bot\node_modules\ws\lib\websocket.js:194:10)
    at TLSSocket.socketOnClose (C:\Users\Rauf\paradox\Discord-OwO-Bot\node_modules\ws\lib\websocket.js:861:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)
[16:01:55] Cluster 0 | Shard 0 disconnected!
```

I just copied secret folder and created new folder named tokens 
![bruhhh](https://user-images.githubusercontent.com/33981808/106462533-497a4d00-64a7-11eb-8a9f-844d7a9a212c.PNG)

any help?

**Comment by Togira123** [comment]
obviously you have entered a wrong bot token?

**Comment by SnapshotMe** [comment]
i have the same problem 
did you guys solved ?
