### ISSUE TITLE
Help me fix this

### ISSUE THREAD

**Issue by conghal334** [ChristopherBThai/Discord-OwO-Bot#222]
Unhandled rejection at: Promise  [object Promise] reason:  TypeError: Cannot read property 'author' of undefined
at Command.checkRaw (xxxxxxxxxxxxx\src\commands\command.js:121:11)
at Command.execute (xxxxxxxxxxxxxx\src\commands\command.js:60:8)

**Comment by Togira123** [comment]
this is basic js, learn js first and you'll be able to solve the problem
