### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by tungdo0602** [ChristopherBThai/Discord-OwO-Bot#376]
Unhandled rejection at: Promise  [object Promise] reason:  Error: ER_NO_SUCH_TABLE: Table 'owo.alter' doesn't exist
    at Sequence._packetToError (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\node_modules\mysql\lib\Pool.js:199:23)
    at D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\src\botHandlers\mysqlHandler.js:14:7
    at new Promise (<anonymous>)
    at exports.query (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\src\botHandlers\mysqlHandler.js:13:9)
    at exports.getAlterCommand (D:\Tung\Code\Nodejs\owo\Discord-OwO-Bot\src\utils\alterUtils.js:18:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by tungdo0602** [comment]
how can i turn off patreon support?

**Comment by tungdo0602** [comment]
pls update your sql file
